config/routes.rb
ServerAti::Application.routes.draw do
  resources :eventos do
		
			collection do
	
				get 'mes' => 'eventos#mes'
				get 'dia' => 'eventos#dia'
				get 'semana' => 'eventos#semana'
				get 'dias' => 'eventos#dias'
				
			end
			
		
	
	end

end

app/models/evento.rb
class Evento < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventos }
    end
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    @evento = Evento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/new
  # GET /eventos/new.json
  def new
    @evento = Evento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/1/edit
  def edit
    @evento = Evento.find(params[:id])
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(params[:evento])

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render json: @evento, status: :created, location: @evento }
      else
        format.html { render action: "new" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /eventos/1
  # PUT /eventos/1.json
  def update
    @evento = Evento.find(params[:id])

    respond_to do |format|
      if @evento.update_attributes(params[:evento])
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento = Evento.find(params[:id])
    @evento.destroy

    respond_to do |format|
      format.html { redirect_to eventos_url }
      format.json { head :ok }
    end
  end
  def mes
  
	@events = Evento.where("strftime('%m',fecha)=?",params[:id]).order('fecha');
	respond_to do |format|
		format.html # new.html.erb
		format.json  { render :json => @events }
	end
	
  end
  def semana
  
	@events = Evento.where("strftime('%W',fecha)=?",params[:id]).order('fecha');
	respond_to do |format|
		format.html # new.html.erb
		format.json  { render :json => @events }
	end
	
  end
  def dia
  
	@events = Evento.where("strftime('%d',fecha)=?",params[:id]).order('fecha');
	respond_to do |format|
		format.html # new.html.erb
		format.json  { render :json => @events }
	end
	
  end
  def dias
  
	@events = Evento.where("julianday(fecha)-julianday('now') between 0 and 7");
	respond_to do |format|
		format.html # new.html.erb
		format.json  { render :json => @events }
	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/dia.html.erb
<h1>Listing eventos Dia</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Fecha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |evento| %>
  <tr>
    <td><%= evento.nombre %></td>
    <td><%= evento.descripcion %></td>
    <td><%= evento.fecha %></td>
    <td><%= link_to 'Show', evento %></td>
    <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
    <td><%= link_to 'Destroy', evento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/dias.html.erb
<h1>Listing eventos 7 dias a partir de hoy</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Fecha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |evento| %>
  <tr>
    <td><%= evento.nombre %></td>
    <td><%= evento.descripcion %></td>
    <td><%= evento.fecha %></td>
    <td><%= link_to 'Show', evento %></td>
    <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
    <td><%= link_to 'Destroy', evento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<h1>Listing eventos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Fecha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @eventos.each do |evento| %>
  <tr>
    <td><%= evento.nombre %></td>
    <td><%= evento.descripcion %></td>
    <td><%= evento.fecha %></td>
    <td><%= link_to 'Show', evento %></td>
    <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
    <td><%= link_to 'Destroy', evento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/mes.html.erb
<h1>Listing eventos Mes</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Fecha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |evento| %>
  <tr>
    <td><%= evento.nombre %></td>
    <td><%= evento.descripcion %></td>
    <td><%= evento.fecha %></td>
    <td><%= link_to 'Show', evento %></td>
    <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
    <td><%= link_to 'Destroy', evento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New evento</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/semana.html.erb
<h1>Listing eventos Semana</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Fecha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |evento| %>
  <tr>
    <td><%= evento.nombre %></td>
    <td><%= evento.descripcion %></td>
    <td><%= evento.fecha %></td>
    <td><%= link_to 'Show', evento %></td>
    <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
    <td><%= link_to 'Destroy', evento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @evento.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @evento.descripcion %>
</p>

<p>
  <b>Fecha:</b>
  <%= @evento.fecha %>
</p>


<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ServerAti</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>